// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CompanyNamespaceWhatever
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public enum Color : sbyte
{
  Red = 1,
  Green = 2,
  Blue = 3,
};

public enum WeaponClassesOrWhatever : byte
{
  NONE = 0,
  Sword = 1,
  Gun = 2,
};

public struct Vec3 : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Vec3 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float X { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
  public float Y { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
  public float Z { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }

  public static Offset<CompanyNamespaceWhatever.Vec3> CreateVec3(FlatBufferBuilder builder, float X, float Y, float Z) {
    builder.Prep(4, 12);
    builder.PutFloat(Z);
    builder.PutFloat(Y);
    builder.PutFloat(X);
    return new Offset<CompanyNamespaceWhatever.Vec3>(builder.Offset);
  }
};

public struct GameDataWhatever : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static GameDataWhatever GetRootAsGameDataWhatever(ByteBuffer _bb) { return GetRootAsGameDataWhatever(_bb, new GameDataWhatever()); }
  public static GameDataWhatever GetRootAsGameDataWhatever(ByteBuffer _bb, GameDataWhatever obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool GameDataWhateverBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "WHAT"); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GameDataWhatever __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CompanyNamespaceWhatever.Vec3? Pos { get { int o = __p.__offset(4); return o != 0 ? (CompanyNamespaceWhatever.Vec3?)(new CompanyNamespaceWhatever.Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public short Mana { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)150; } }
  public short Hp { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)100; } }
  public string Name { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(10); }
  public byte Inventory(int j) { int o = __p.__offset(12); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int InventoryLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetInventoryBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetInventoryBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetInventoryArray() { return __p.__vector_as_array<byte>(12); }
  public CompanyNamespaceWhatever.Color Color { get { int o = __p.__offset(14); return o != 0 ? (CompanyNamespaceWhatever.Color)__p.bb.GetSbyte(o + __p.bb_pos) : CompanyNamespaceWhatever.Color.Blue; } }
  public CompanyNamespaceWhatever.WeaponClassesOrWhatever WeaponType { get { int o = __p.__offset(16); return o != 0 ? (CompanyNamespaceWhatever.WeaponClassesOrWhatever)__p.bb.Get(o + __p.bb_pos) : CompanyNamespaceWhatever.WeaponClassesOrWhatever.NONE; } }
  public TTable? Weapon<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(18); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }

  public static void StartGameDataWhatever(FlatBufferBuilder builder) { builder.StartTable(8); }
  public static void AddPos(FlatBufferBuilder builder, Offset<CompanyNamespaceWhatever.Vec3> posOffset) { builder.AddStruct(0, posOffset.Value, 0); }
  public static void AddMana(FlatBufferBuilder builder, short mana) { builder.AddShort(1, mana, 150); }
  public static void AddHp(FlatBufferBuilder builder, short hp) { builder.AddShort(2, hp, 100); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(3, nameOffset.Value, 0); }
  public static void AddInventory(FlatBufferBuilder builder, VectorOffset inventoryOffset) { builder.AddOffset(4, inventoryOffset.Value, 0); }
  public static VectorOffset CreateInventoryVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateInventoryVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static void StartInventoryVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static void AddColor(FlatBufferBuilder builder, CompanyNamespaceWhatever.Color color) { builder.AddSbyte(5, (sbyte)color, 3); }
  public static void AddWeaponType(FlatBufferBuilder builder, CompanyNamespaceWhatever.WeaponClassesOrWhatever weaponType) { builder.AddByte(6, (byte)weaponType, 0); }
  public static void AddWeapon(FlatBufferBuilder builder, int weaponOffset) { builder.AddOffset(7, weaponOffset, 0); }
  public static Offset<CompanyNamespaceWhatever.GameDataWhatever> EndGameDataWhatever(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CompanyNamespaceWhatever.GameDataWhatever>(o);
  }
  public static void FinishGameDataWhateverBuffer(FlatBufferBuilder builder, Offset<CompanyNamespaceWhatever.GameDataWhatever> offset) { builder.Finish(offset.Value, "WHAT"); }
  public static void FinishSizePrefixedGameDataWhateverBuffer(FlatBufferBuilder builder, Offset<CompanyNamespaceWhatever.GameDataWhatever> offset) { builder.FinishSizePrefixed(offset.Value, "WHAT"); }
};

public struct Sword : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static Sword GetRootAsSword(ByteBuffer _bb) { return GetRootAsSword(_bb, new Sword()); }
  public static Sword GetRootAsSword(ByteBuffer _bb, Sword obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Sword __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Damage { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)10; } }
  public short Distance { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)5; } }

  public static Offset<CompanyNamespaceWhatever.Sword> CreateSword(FlatBufferBuilder builder,
      int damage = 10,
      short distance = 5) {
    builder.StartTable(2);
    Sword.AddDamage(builder, damage);
    Sword.AddDistance(builder, distance);
    return Sword.EndSword(builder);
  }

  public static void StartSword(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddDamage(FlatBufferBuilder builder, int damage) { builder.AddInt(0, damage, 10); }
  public static void AddDistance(FlatBufferBuilder builder, short distance) { builder.AddShort(1, distance, 5); }
  public static Offset<CompanyNamespaceWhatever.Sword> EndSword(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CompanyNamespaceWhatever.Sword>(o);
  }
};

public struct Gun : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static Gun GetRootAsGun(ByteBuffer _bb) { return GetRootAsGun(_bb, new Gun()); }
  public static Gun GetRootAsGun(ByteBuffer _bb, Gun obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Gun __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Damage { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)500; } }
  public short Reloadspeed { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)2; } }

  public static Offset<CompanyNamespaceWhatever.Gun> CreateGun(FlatBufferBuilder builder,
      int damage = 500,
      short reloadspeed = 2) {
    builder.StartTable(2);
    Gun.AddDamage(builder, damage);
    Gun.AddReloadspeed(builder, reloadspeed);
    return Gun.EndGun(builder);
  }

  public static void StartGun(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddDamage(FlatBufferBuilder builder, int damage) { builder.AddInt(0, damage, 500); }
  public static void AddReloadspeed(FlatBufferBuilder builder, short reloadspeed) { builder.AddShort(1, reloadspeed, 2); }
  public static Offset<CompanyNamespaceWhatever.Gun> EndGun(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CompanyNamespaceWhatever.Gun>(o);
  }
};


}
